// Generated by scripts/gen-clients.ts from schema/easl-api.json. Do not edit.

package api

// SchemaVersion is the `version` of the schema this build was generated from.
const SchemaVersion = 1

// Error codes of a failed response's `error.code`, with what each means.
const (
	// params failed schema validation.
	CodeInvalidParams = "invalid_params"
	// referenced object, mention, or agent does not exist.
	CodeNotFound = "not_found"
	// rev mismatch on update; re-read and retry.
	CodeConflict = "conflict"
	// method known but not implemented by this build.
	CodeUnsupported = "unsupported"
	// target exists but cannot act right now (e.g. a terminal tile without an attached surface), or the app is not running.
	CodeUnavailable = "unavailable"
	// agent.wait deadline passed before the agent reached a requested state.
	CodeTimeout = "timeout"
	// unexpected server failure.
	CodeInternal = "internal"
)

// ParamSpec is a method's params: every name it accepts (`params.properties`, in schema order) and the required ones.
type ParamSpec struct {
	Accepted []string
	Required []string
}

// Methods is each method's ParamSpec: what the server checks every request against, and names in its `invalid_params` errors.
var Methods = map[string]ParamSpec{
	"system.ping": {
		Accepted: nil,
		Required: nil,
	},
	"board.get": {
		Accepted: []string{"board", "since", "branch"},
		Required: nil,
	},
	"board.history": {
		Accepted: []string{"board", "since", "limit", "kinds"},
		Required: nil,
	},
	"board.list": {
		Accepted: nil,
		Required: nil,
	},
	"board.open": {
		Accepted: []string{"root", "select"},
		Required: []string{"root"},
	},
	"board.export": {
		Accepted: []string{"board", "path"},
		Required: nil,
	},
	"object.get": {
		Accepted: []string{"id", "as", "since"},
		Required: []string{"id"},
	},
	"object.find": {
		Accepted: []string{"board", "key", "keyPrefix", "as"},
		Required: nil,
	},
	"object.create": {
		Accepted: []string{"board", "type", "props", "frame", "size", "parent", "caller"},
		Required: []string{"type", "props"},
	},
	"object.update": {
		Accepted: []string{"id", "rev", "frame", "size", "props", "caller"},
		Required: []string{"id"},
	},
	"object.upsert": {
		Accepted: []string{"board", "key", "type", "props", "frame", "size", "caller"},
		Required: []string{"key", "type", "props"},
	},
	"object.delete": {
		Accepted: []string{"id", "caller"},
		Required: []string{"id"},
	},
	"object.measure": {
		Accepted: []string{"board", "type", "props", "width", "caller"},
		Required: []string{"type", "props"},
	},
	"object.reload": {
		Accepted: []string{"id", "timeoutMs", "caller"},
		Required: []string{"id"},
	},
	"object.batch": {
		Accepted: []string{"board", "ops", "caller"},
		Required: []string{"ops"},
	},
	"layout.place": {
		Accepted: []string{"id", "near", "side", "gap", "align", "caller"},
		Required: []string{"id", "near"},
	},
	"layout.stack": {
		Accepted: []string{"ids", "direction", "gap", "wrapAt", "align", "origin", "caller"},
		Required: []string{"ids"},
	},
	"layout.translate": {
		Accepted: []string{"ids", "dx", "dy", "caller"},
		Required: []string{"ids", "dx", "dy"},
	},
	"layout.grid": {
		Accepted: []string{"cells", "colGap", "rowGap", "colAlign", "rowAlign", "origin", "caller"},
		Required: []string{"cells"},
	},
	"layout.check": {
		Accepted: []string{"board", "ids", "rect", "caller"},
		Required: nil,
	},
	"tray.list": {
		Accepted: []string{"board"},
		Required: nil,
	},
	"tray.stage": {
		Accepted: []string{"target", "board"},
		Required: []string{"target"},
	},
	"tray.unstage": {
		Accepted: []string{"id"},
		Required: []string{"id"},
	},
	"tray.drain": {
		Accepted: []string{"board", "caller", "peek"},
		Required: nil,
	},
	"tray.commit": {
		Accepted: []string{"board", "ids"},
		Required: []string{"ids"},
	},
	"agent.report": {
		Accepted: []string{"tile", "kind", "state", "message", "seq", "source", "call", "final", "serial", "error"},
		Required: []string{"tile", "kind", "state"},
	},
	"agent.report_session": {
		Accepted: []string{"tile", "kind", "sessionId", "sessionPath"},
		Required: []string{"tile", "kind"},
	},
	"agent.release": {
		Accepted: []string{"tile", "kind", "source"},
		Required: []string{"tile", "kind"},
	},
	"agent.list": {
		Accepted: nil,
		Required: nil,
	},
	"agent.prompt": {
		Accepted: []string{"target", "text", "mentions", "caller", "force"},
		Required: []string{"target", "text"},
	},
	"agent.wait": {
		Accepted: []string{"target", "until", "timeoutMs"},
		Required: []string{"target"},
	},
	"agent.read": {
		Accepted: []string{"target", "lines", "since", "block", "final"},
		Required: []string{"target"},
	},
	"follow.report": {
		Accepted: []string{"tile", "path", "range", "changes", "action"},
		Required: []string{"tile", "path", "action"},
	},
	"view.attention": {
		Accepted: []string{"id", "message", "clear", "caller"},
		Required: []string{"id"},
	},
	"view.get": {
		Accepted: []string{"board"},
		Required: nil,
	},
	"view.open_url": {
		Accepted: []string{"url", "board", "caller"},
		Required: []string{"url"},
	},
	"view.render": {
		Accepted: []string{"board", "target", "scale", "full", "exclude", "padding", "out", "format", "timeoutMs"},
		Required: []string{"target"},
	},
	"view.snapshot": {
		Accepted: []string{"board", "out", "format"},
		Required: nil,
	},
	"events.subscribe": {
		Accepted: []string{"board", "events"},
		Required: nil,
	},
}

// Id: Prefixed id, e.g. obj_01H…, men_…
type Id = string

type Frame struct {
	X float64 `json:"x"`
	Y float64 `json:"y"`
	W float64 `json:"w"`
	H float64 `json:"h"`
}

// Actor is a union of JSON objects (variants: "user", "agent"); decode it as a generic map.
type Actor = map[string]any

// LineRange: 1-based inclusive line range
type LineRange struct {
	Start int `json:"start"`
	End   int `json:"end"`
}

// AnchorState: live: the anchored lines are where written; relocated: found elsewhere by content, or longer or shorter by lines inserted or removed inside; stale: the content is gone (a note shows its last text dimmed, a code tile an untinted range); applied: a proposal whose text the file already reads; missing: no such file or commit
type AnchorState string

const (
	AnchorStateLive      AnchorState = "live"
	AnchorStateRelocated AnchorState = "relocated"
	AnchorStateStale     AnchorState = "stale"
	AnchorStateApplied   AnchorState = "applied"
	AnchorStateMissing   AnchorState = "missing"
)

// AnchorStatus: how an anchored range (a note fence, a code tile's range) resolves against disk now
type AnchorStatus struct {
	State AnchorState `json:"state"`
	// where it resolved (absent when stale or missing)
	Range *LineRange `json:"range,omitempty"`
	// relocated: the range as written
	Written *LineRange `json:"written,omitempty"`
	// stale or missing: why
	Reason *string `json:"reason,omitempty"`
}

// Zoom: how big the tile's content draws inside its frame, in place (1.5 is 150%): the frame never changes with it and the title bar stays at 1×; the body lays out at body ÷ zoom and draws zoom× (terminal: bigger text, fewer columns and rows, the program gets the new grid; browser, html: like page zoom, the viewport is body ÷ zoom; code, note, changes: text bigger and rewrapped; diagram: bigger). An object.update that sets it never changes the frame: resize the tile for more room. Out-of-range values clamp; 1 is written as absent. Not on image tiles (the picture is already fitted to the frame; make the tile bigger). The user sets it with the title bar's − % + (the % resets to 100%) or Object › Content Zoom (Zoom Content In ⌃⌘=, Out ⌃⌘-, the presets, Reset Content Zoom ⌃⌘0). Replaces `scale`, which object.create/update/upsert/batch and object.measure reject with invalid_params
type Zoom = float64

type Lifecycle struct {
	// One of "working", "blocked", "idle", "done", "unknown".
	State   string  `json:"state"`
	Message *string `json:"message,omitempty"`
	Seen    *bool   `json:"seen,omitempty"`
	// a `working` or `blocked` the app restored from before it last closed, which the agent hasn't confirmed since (no report, live or spooled, yet): what it was, maybe not what it is now. `agent.prompt` refuses a restored `working` (read the screen first) unless `force`
	Restored *bool `json:"restored,omitempty"`
	// an agent without a lifecycle integration: its terminal notifications (OSC 9/777, a bell) set `done` (`idle` while the user looks), Return typed into it or `agent.prompt` sets `unknown` until the next one; never `working` or `blocked`
	Via *string `json:"via,omitempty"`
}

// ObjectKey: any object: a name a script finds it by (`object.find`, `object.upsert`), e.g. a ticket id on the group that is its region. Unique on its board: taking one another object holds is `conflict`, naming the holder; null removes it
type ObjectKey = string

// TerminalPropsAgent: the agent reporting in this tile. When the tile's session is gone (a reboot) it resumes `sessionId` (`omp --resume`, `claude --resume`, `codex resume`). Removed when the agent exits (agent.release)
type TerminalPropsAgent struct {
	Kind        string  `json:"kind"`
	SessionID   *string `json:"sessionId,omitempty"`
	SessionPath *string `json:"sessionPath,omitempty"`
}

type TerminalProps struct {
	Cwd string `json:"cwd"`
	// argv run inside the zmx session
	Command    []string `json:"command"`
	ZmxSession *string  `json:"zmxSession,omitempty"`
	Title      *string  `json:"title,omitempty"`
	// a name other agents address this terminal by (agent.prompt/wait/read `target`)
	Name *string `json:"name,omitempty"`
	// the agent reporting in this tile. When the tile's session is gone (a reboot) it resumes `sessionId` (`omp --resume`, `claude --resume`, `codex resume`). Removed when the agent exits (agent.release)
	Agent     *TerminalPropsAgent `json:"agent,omitempty"`
	Lifecycle *Lifecycle          `json:"lifecycle,omitempty"`
	// follow mode: false after the user closes the terminal's follow tile (or turns Follow Files off); follow.report is then ignored until it is true again
	Follow *bool      `json:"follow,omitempty"`
	Zoom   *Zoom      `json:"zoom,omitempty"`
	Key    *ObjectKey `json:"key,omitempty"`
	// written by easl: the top level of the worktree of the board's repository the terminal was created in (its `cwd`'s); what it started in, not updated when the shell moves
	Worktree *string `json:"worktree,omitempty"`
	// written by easl with `worktree`: the branch checked out there when the terminal was created; absent on a detached HEAD
	Branch *string `json:"branch,omitempty"`
}

type BrowserProps struct {
	URL string `json:"url"`
	// names the tile; the app never overwrites it
	Title *string `json:"title,omitempty"`
	// written by the app: the page's own title; shown when `title` is unset; never bumps rev
	PageTitle *string `json:"pageTitle,omitempty"`
	Zoom      *Zoom   `json:"zoom,omitempty"`
	// a named browser profile: its own cookies, logins and storage, shared by every tile that names it; absent: the default profile. Tiles a page opens (links, popups) take it
	Profile *string `json:"profile,omitempty"`
	// a page served from this Mac (localhost, 127.x, [::1], a .localhost name, a file) reloads when a file under the board root (a file page: its folder) changes; hidden files and folders and node_modules don't count
	ReloadOnChange *bool      `json:"reloadOnChange,omitempty"`
	Key            *ObjectKey `json:"key,omitempty"`
}

type CodePropsHistory struct {
	Path  string     `json:"path"`
	Range *LineRange `json:"range,omitempty"`
	// One of "read", "edit", "write", "lsp", "search".
	Action string `json:"action"`
}

type CodeProps struct {
	// path relative to the board root (relative to your own checkout when you work in another worktree of the board's repository: stored absolute there), or absolute
	Path string `json:"path"`
	// lines to scroll to and tint; the tile always shows the whole file. Kept on the code it showed: when lines are inserted or removed above or inside it, the tile re-finds it by content and writes the moved range back (no rev, no undo step); code that is gone leaves it untinted with a stale warning in the header (not follow tiles or pinned tiles)
	Range *LineRange `json:"range,omitempty"`
	// the range's first line (trimmed), which re-finds the range after lines move; written back by the tile, or given with the range. An update that changes range or path without an anchor drops it
	Anchor *string `json:"anchor,omitempty"`
	// the declaration the range shows; with a range it only names it, and `size: "fit"` fits the range
	Symbol *string `json:"symbol,omitempty"`
	// one-line subtitle under the tile's header (plain text, `inline code` allowed); never wraps: object.measure and size "fit" widen the tile to show all of it, and layout.check reports a caption its frame cuts off (`truncated`)
	Caption *string `json:"caption,omitempty"`
	// gutter signs show changes against this: merge-base | head | <sha>
	DiffBase *string `json:"diffBase,omitempty"`
	// terminal tile this follow tile tracks
	FollowOf *Id `json:"followOf,omitempty"`
	// follow tiles: what the agent last did at this location One of "read", "edit", "write", "lsp", "search".
	LastAction *string `json:"lastAction,omitempty"`
	// follow tiles: the hunks the agent's last edit here changed (`follow.report` `changes`), which the tile flashes
	LastChanges []LineRange `json:"lastChanges,omitempty"`
	// follow tiles: recent locations, newest first, without repeats; a location once edited or written keeps that action when read again, and past 8 entries the oldest reads go first, so every edit of a burst stays listed
	History []CodePropsHistory `json:"history,omitempty"`
	// a branch (or any ref) the tile is anchored to instead of one checkout; `path` is relative to the board root's place in the repository (an absolute path in any worktree of the repository means the same repo path). While a worktree of the repository has the ref checked out the tile reads that working tree live: gutter against `diffBase` (default its merge-base), edits reload (header: "live in <worktree>"). Otherwise it reads git objects at the ref, read-only like `pinnedCommit` ("<ref> @ <sha>"). Once the ref no longer resolves (worktree and branch deleted) it reads `refSha`: when the default branch contains it, at the commit that merged it ("merged in <sha>"), else at `refSha` itself ("branch gone, showing <sha>") while its objects exist. `pinnedCommit`, when also set, wins and the ref is ignored. A ref that resolves to nothing (and no `refSha` whose objects remain) is `not_found` on create or update
	Ref *string `json:"ref,omitempty"`
	// written by easl: the full SHA `ref` last resolved to (the live worktree's HEAD, or the ref's commit), recorded on every resolve without a rev or undo step, so the tile keeps reading once its worktree and branch are deleted. May be given with `ref` (e.g. by a script that knows the tip)
	RefSha *string `json:"refSha,omitempty"`
	// a commit (sha, tag, branch, e.g. `HEAD~3` or a fetched `pull/12/head`'s sha): the tile shows the file as of that commit, read-only, with no diff gutter or base picker (header: "pinned at <sha>"); measure, fit, layout.check, line anchors, and renders use that text. The working tree plays no part. Unknown commit or file: the tile says so, and a create or update that needs its text (`size: fit`, a symbol) fails with `not_found`. A path in another worktree of the repository (absolute) is read in that worktree
	PinnedCommit *string    `json:"pinnedCommit,omitempty"`
	Zoom         *Zoom      `json:"zoom,omitempty"`
	Key          *ObjectKey `json:"key,omitempty"`
}

type NoteProps struct {
	// Markdown. Code fence info strings pick a mode: ```ts file=path#L10-40``` (or symbol=Name, optionally with file=) is a live excerpt of the file; add `propose` to render the fence body as a diff against that range; file=path@<sha>#L10-40 pins to a commit; anchor="first line text" re-finds the range when lines move. Any other fence is free-written. path:line references are clickable wherever they appear: prose, headings, table cells, inline code, free-written fences.
	Markdown string `json:"markdown"`
	// shown in the tile's title bar (default "Note") and Go to
	Title *string `json:"title,omitempty"`
	// a branch (or any ref) whose tree the note's paths resolve in, instead of `root` (which it overrides): the worktree that has it checked out, live, else git objects at the ref, falling back like CodeProps.ref once it is merged or deleted (via `refSha`). Excerpt fences without their own `@<sha>` read there; path:line links open code tiles with the same `ref`. The markdown stays inline, and images still load from the board's checkout when no worktree has the ref
	Ref *string `json:"ref,omitempty"`
	// written by easl: the SHA `ref` last resolved to (as CodeProps.refSha)
	RefSha *string `json:"refSha,omitempty"`
	// the directory the note's relative paths resolve against (path:line and markdown links, excerpt fences, images): the board's checkout or another worktree of its repository, absolute or board-relative (e.g. ../wt-agent). Default: the board root; a note an agent creates from another worktree than the board's gets that worktree (the same place in it as the board root). Anything else is invalid_params
	Root *string    `json:"root,omitempty"`
	Zoom *Zoom      `json:"zoom,omitempty"`
	Key  *ObjectKey `json:"key,omitempty"`
}

type HtmlProps struct {
	// page body (or a full document); the kit (Tailwind, Mermaid, canvas-code/link/decisions/compare) is preloaded
	HTML  string  `json:"html"`
	Title *string `json:"title,omitempty"`
	// a branch (or any ref) whose tree canvas-code excerpts and canvas-link resolve in, instead of `root`: as NoteProps.ref. The page body stays inline; img and other page files load from the live worktree, else the board's checkout
	Ref *string `json:"ref,omitempty"`
	// written by easl: the SHA `ref` last resolved to (as CodeProps.refSha)
	RefSha *string `json:"refSha,omitempty"`
	// the directory the page's relative paths resolve against (canvas-link, canvas-code, img): as NoteProps.root
	Root         *string  `json:"root,omitempty"`
	AllowNetwork []string `json:"allowNetwork,omitempty"`
	// tile state written by the page through its channel (e.g. canvas-decisions choices by key); at most 256 KiB
	State map[string]any `json:"state,omitempty"`
	Zoom  *Zoom          `json:"zoom,omitempty"`
	Key   *ObjectKey     `json:"key,omitempty"`
}

type ChangesPropsReviewed struct {
	// revert: the user's Discard; unstage: taken out of the index One of "stage", "unstage", "revert".
	Action *string `json:"action,omitempty"`
	// board-relative, else absolute
	Path *string `json:"path,omitempty"`
	// lines: some lines of one hunk the user selected One of "hunk", "lines", "file".
	Scope *string `json:"scope,omitempty"`
	// One of "added", "modified", "deleted", "renamed".
	Status *string `json:"status,omitempty"`
	// the hunk's stable id as `object.get` gave it (scope hunk or lines)
	Hunk *string `json:"hunk,omitempty"`
	// the hunk's `@@ -a,b +c,d @@` at the time (scope hunk or lines)
	Header *string `json:"header,omitempty"`
	// how the tile named the hunk: `Lines 15–46`
	Label *string `json:"label,omitempty"`
	// added lines the action covered
	Added *int `json:"added,omitempty"`
	// removed lines the action covered
	Removed *int `json:"removed,omitempty"`
	// the unified patch applied (at most 200 lines): staged as is to the index; a discard's is the base → working tree diff (HEAD → working tree against an older base) applied reversed (`applied: reversed`), so its `-` lines are what came back and its `+` lines what went; an unstage's is the HEAD → index diff applied reversed to the index
	Patch   *string `json:"patch,omitempty"`
	Applied *string `json:"applied,omitempty"`
	// the patch had more lines
	Truncated *bool `json:"truncated,omitempty"`
}

type ChangesProps struct {
	// another worktree of the board's repository to review (absolute or board-relative, e.g. ../wt-agent; default: the board root, or your own checkout when you work in another worktree of the board's repository). Anything that isn't a worktree of the board's repository lists nothing and says so. Its files have absolute paths
	Root *string `json:"root,omitempty"`
	// what the changes are against: HEAD (the uncommitted work, staged or not: what an agent just did) | merge-base (with the default branch: everything the branch changed, a PR's view) | a commit or ref. The user picks it in the tile's header too. Against anything but HEAD, committed hunks can't be discarded. With `head` or `ref` it defaults to merge-base, and the diff is against the merge-base of `head` with it (`git diff base...head`, a PR's view)
	Base *string `json:"base,omitempty"`
	// compare two commits instead of a worktree: any commit or ref (a branch, origin/x, a fetched pull/N/head) against its merge-base with `base` (e.g. {"base": "origin/main", "head": "fm/rel-12389"}). Read from git objects, no checkout; renames and deletions included; read-only: no Stage, Unstage, or Discard. Clicking a line opens a code tile pinned to that side's commit. A ref the repository lacks lists nothing and names the exact `git fetch` that brings it: easl never fetches
	Head *string `json:"head,omitempty"`
	// a branch, instead of `root`: while a worktree of the board's repository has it checked out, that worktree (live, as `root`); otherwise its commits against `base` from git objects, read-only (as `head`). Once the branch is gone it reads `refSha`, and says `merged in <sha>` or `branch gone`. object.create/update resolve it and record `refSha`; a ref that resolves to nothing is not_found, naming the `git fetch` that brings it
	Ref *string `json:"ref,omitempty"`
	// written by the tile: the commit `ref` named when the tile last read it, what it falls back to once the branch is deleted
	RefSha *string `json:"refSha,omitempty"`
	// files or directories to limit it to, relative to `root` (default the board root) or absolute (default: all of it); a path outside that worktree lists nothing and says so
	Paths []string `json:"paths,omitempty"`
	Title *string  `json:"title,omitempty"`
	// written by the tile: the Stage, Unstage, and Discard actions the user took, oldest first (⌘Z of one removes its entry). Agents read it; writing it changes nothing in git
	Reviewed []ChangesPropsReviewed `json:"reviewed,omitempty"`
	// written by the tile: files the user marked Viewed (path → a fingerprint of their diff then). A file counts as viewed (folded, `changes.files[].viewed`) only while its diff is unchanged
	Viewed map[string]string `json:"viewed,omitempty"`
	Zoom   *Zoom             `json:"zoom,omitempty"`
	Key    *ObjectKey        `json:"key,omitempty"`
}

type ImageProps struct {
	// the image file: board-relative or absolute (png, jpg, gif, webp, heic, tiff, bmp, svg, or a pdf's first page). The tile shows it at its aspect ratio and reloads when the file changes on disk, so re-save a chart to the same path to update it
	Path string `json:"path"`
	// one line under the picture (truncated when longer than the tile is wide)
	Caption *string `json:"caption,omitempty"`
	// shown in the title bar and Go to (default: the file name)
	Title *string    `json:"title,omitempty"`
	Key   *ObjectKey `json:"key,omitempty"`
}

type DiagramPropsGraphNodesExcerpt struct {
	Line *int    `json:"line,omitempty"`
	Text *string `json:"text,omitempty"`
}

type DiagramPropsGraphNodes struct {
	// `path#Container.name`, stable while the symbol exists (not its line); what `expanded` and arrow ends name
	ID        string  `json:"id"`
	Name      string  `json:"name"`
	Container *string `json:"container,omitempty"`
	// LSP symbol kind: method, function, constructor, …
	Kind string `json:"kind"`
	// board-relative
	Path string `json:"path"`
	// 1-based line of its name
	Line int `json:"line"`
	// its whole declaration
	Lines   LineRange                       `json:"lines"`
	Excerpt []DiagramPropsGraphNodesExcerpt `json:"excerpt"`
	// columns from the root (0): callers negative, callees positive
	Level int `json:"level"`
	// its symbol is gone from its file: shown as it last was, badged
	Stale *bool `json:"stale,omitempty"`
	// its next level hasn't been asked for: a click (or adding its id to `expanded`) opens it
	Expandable *bool `json:"expandable,omitempty"`
	// opened past `depth` (`expanded`)
	Expanded *bool `json:"expanded,omitempty"`
}

type DiagramPropsGraphEdges struct {
	// the caller's node id
	From string `json:"from"`
	// the callee's node id
	To string `json:"to"`
	// 1-based lines of the calls, in the caller's file
	Lines []int `json:"lines"`
	Stale *bool `json:"stale,omitempty"`
}

// DiagramPropsGraph: written by the app (never an undo step, no rev): the graph as last computed. Agents read it; writing it changes nothing (the next computation replaces it)
type DiagramPropsGraph struct {
	// the kind, path, symbol, line and direction it was computed for
	Aim map[string]any `json:"aim,omitempty"`
	// the root node's id
	Root  *string                  `json:"root,omitempty"`
	Nodes []DiagramPropsGraphNodes `json:"nodes,omitempty"`
	Edges []DiagramPropsGraphEdges `json:"edges,omitempty"`
	// why the graph is empty or old: no language server for the file, the symbol isn't found, the server failed or has no call hierarchy. The last good graph stays
	Error *string `json:"error,omitempty"`
	// nodes left out past 60
	Omitted    *int    `json:"omitted,omitempty"`
	ComputedAt *string `json:"computedAt,omitempty"`
}

// DiagramProps: A diagram computed from the code by the language server and kept live. kind calls: a function (the root) and its callers (direction incoming), callees (outgoing) or both, `depth` levels out, as a layered graph of symbol-anchored nodes (name, container, path:line, 1-3 excerpt lines: a caller's calls, else the signature). Only functions in the files of the checkout it is of are nodes: the one its root's file lies in (a worktree's file: that worktree), else yours when you work in another worktree, else the board root's. The graph is computed when the tile is created or re-aimed, again when a file it shows changes on disk, and on `object.reload` (which waits for it); nodes re-resolve by symbol, so code moving keeps them, and a node whose symbol is gone from its file stays with a stale badge (`graph.nodes[].stale`) until it is back or the diagram is aimed elsewhere. Clicking a node with + opens its next level (`expanded`, undoable); its path:line opens the code; a Hyper-click mentions its symbol and lines (a code mention) or the excerpt line under the pointer. An arrow end binds to a node with `{object, node}`.
type DiagramProps struct {
	// what the diagram is of; more kinds (types, pipelines) will come One of "calls".
	Kind *string `json:"kind,omitempty"`
	// the root function: `Type.member` or a bare name, parameter labels optional (`SocketServer.start`, `AgentReportSpool.read`, `read(from:tiles:)`). Without `path`, the board's files are searched for its declaration
	Symbol *string `json:"symbol,omitempty"`
	// the file declaring the root, board-relative (relative to your own checkout when you work in another worktree) or absolute
	Path *string `json:"path,omitempty"`
	// without `symbol`: the root's declaration line (or a line inside its body) in `path`. Only the first computation reads it: after that the root is re-found by the symbol found there
	Line *int `json:"line,omitempty"`
	// incoming: who calls it (callers left of it); outgoing: what it calls (right of it); both One of "incoming", "outgoing", "both".
	Direction *string `json:"direction,omitempty"`
	// levels shown each side of the root without clicking; nodes on the last level show + when not yet expanded
	Depth *int `json:"depth,omitempty"`
	// node ids (`graph.nodes[].id`) opened one level past `depth`; a click toggles one
	Expanded []string `json:"expanded,omitempty"`
	// default: `Callers of <symbol>` (`Calls from`, `Calls around`)
	Title *string `json:"title,omitempty"`
	// written by the app (never an undo step, no rev): the graph as last computed. Agents read it; writing it changes nothing (the next computation replaces it)
	Graph *DiagramPropsGraph `json:"graph,omitempty"`
	Zoom  *Zoom              `json:"zoom,omitempty"`
	Key   *ObjectKey         `json:"key,omitempty"`
}

type ShapeProps struct {
	// One of "rect", "ellipse", "text", "ink".
	Kind string  `json:"kind"`
	Text *string `json:"text,omitempty"`
	// ink points [x, y, pressure?] in object-local coordinates
	Points [][]float64 `json:"points,omitempty"`
	// palette name (black, grey, blue, green, orange, red, violet) or #rrggbb
	Color *string `json:"color,omitempty"`
	// rect/ellipse interior; only filled interiors hit-test, so an unfilled shape never blocks what is beneath it One of "none", "semi", "solid".
	Fill *string `json:"fill,omitempty"`
	// text shapes only: a multiplier of the 20-pt text font; the frame grows with it (a corner drag on a text shape scales text and box together, as does Object › Content Zoom). Rect and ellipse labels don't take it; ignored on other kinds
	TextSize *float64   `json:"textSize,omitempty"`
	Key      *ObjectKey `json:"key,omitempty"`
}

// Binding is a union of JSON objects (variants: "", ""); decode it as a generic map.
type Binding = map[string]any

type ArrowProps struct {
	From Binding `json:"from"`
	To   Binding `json:"to"`
	// semantic edge type, e.g. hypothesis_about, calls, depends_on
	Relation *string `json:"relation,omitempty"`
	// caption drawn beside the route. Absent: the arrow shows its `relation` (secondary color) instead; "" shows no caption
	Label *string `json:"label,omitempty"`
	// palette name or #rrggbb, as ShapeProps.color
	Color *string `json:"color,omitempty"`
	// straight: one segment between the facing sides; orthogonal: horizontal/vertical segments with one jog; avoid: horizontal/vertical segments around every tile (and text or filled shape) in the way, routed together with the board's other avoid arrows: arrows sharing a side get their own ports, arrows sharing a channel run in parallel tracks, and they follow their group's `flow`. Arrows between the same two objects (either direction) are drawn apart automatically; labels sit beside their own route, clear of boxes, group titles, other arrows and other labels where possible (else a short leader away). One of "straight", "orthogonal", "avoid".
	Route *string    `json:"route,omitempty"`
	Key   *ObjectKey `json:"key,omitempty"`
}

// GroupProps: A group is a region: its frame is always its members' bounds plus `padding`, with a 32 pt title band on top, kept current as members move, resize, or go away (a `frame` passed for a group is ignored). `object.get --as graph` encloses what lies inside that frame.
type GroupProps struct {
	Members []Id `json:"members"`
	// shown in the title band; the band is the group's drag handle
	Title *string `json:"title,omitempty"`
	// palette name or #rrggbb, as ShapeProps.color; tints the region and title
	Color *string `json:"color,omitempty"`
	// space between the members' bounds and the region's edge
	Padding *float64 `json:"padding,omitempty"`
	// which way the diagram inside reads: `avoid` arrows among the members leave the side of their source facing downstream and enter their target's upstream side where they can. Absent: inferred from the way arrows between groups point One of "right", "down", "left", "up".
	Flow *string    `json:"flow,omitempty"`
	Key  *ObjectKey `json:"key,omitempty"`
}

// FitFrame: with size: fit (or for a new note), where the object goes; the rest of its frame is measured
type FitFrame struct {
	X float64 `json:"x"`
	Y float64 `json:"y"`
	// wrap width for notes and text; for code the widest the tile may get (default 960), past which long lines wrap; for html the width the page lays out at (default 640)
	W *float64 `json:"w,omitempty"`
}

// SizeFrame: just a size: the object gets it and is placed as without a frame (the free spot nearest the calling agent's terminal)
type SizeFrame struct {
	W float64 `json:"w"`
	H float64 `json:"h"`
}

// FramePatch: any of x, y, w, h; the rest keep their current values (with size: fit, w is the wrap or widest width and h is measured)
type FramePatch struct {
	X *float64 `json:"x,omitempty"`
	Y *float64 `json:"y,omitempty"`
	W *float64 `json:"w,omitempty"`
	H *float64 `json:"h,omitempty"`
}

type Size struct {
	W float64 `json:"w"`
	H float64 `json:"h"`
}

type ObjectType string

const (
	ObjectTypeTerminal ObjectType = "terminal"
	ObjectTypeBrowser  ObjectType = "browser"
	ObjectTypeCode     ObjectType = "code"
	ObjectTypeNote     ObjectType = "note"
	ObjectTypeHtml     ObjectType = "html"
	ObjectTypeChanges  ObjectType = "changes"
	ObjectTypeImage    ObjectType = "image"
	ObjectTypeDiagram  ObjectType = "diagram"
	ObjectTypeShape    ObjectType = "shape"
	ObjectTypeArrow    ObjectType = "arrow"
	ObjectTypeGroup    ObjectType = "group"
)

type CanvasObject struct {
	ID   Id         `json:"id"`
	Type ObjectType `json:"type"`
	// the whole box the object draws; an arrow's is the bounds of its routed line as drawn (bound ends follow what they point at)
	Frame     Frame   `json:"frame"`
	Z         float64 `json:"z"`
	Rev       int     `json:"rev"`
	Parent    *Id     `json:"parent,omitempty"`
	CreatedBy Actor   `json:"createdBy"`
	UpdatedBy Actor   `json:"updatedBy,omitempty"`
	CreatedAt string  `json:"createdAt"`
	UpdatedAt string  `json:"updatedAt"`
	// one of TerminalProps | BrowserProps | CodeProps | NoteProps | HtmlProps | ChangesProps | ImageProps | DiagramProps | ShapeProps | ArrowProps | GroupProps, selected by type (`easl methods CodeProps` lists one)
	Props map[string]any `json:"props"`
}

type PageLogEntry struct {
	// order within the page's document
	Seq  int    `json:"seq"`
	Time string `json:"time"`
	// a console message; an uncaught error or unhandled promise rejection; a request that failed (HTTP status 400 or more, a network error, a resource that didn't load) One of "console", "exception", "request".
	Kind string `json:"kind"`
	// exceptions and failed requests are `error` One of "log", "info", "warn", "error", "debug".
	Level string `json:"level"`
	// the message as the console prints it (up to 1,000 characters), or `METHOD url → status`
	Text string `json:"text"`
	// `url:line:column` of the code that logged (warnings and errors) or threw
	Source *string `json:"source,omitempty"`
	Stack  *string `json:"stack,omitempty"`
	Method *string `json:"method,omitempty"`
	// a failed request's URL
	URL *string `json:"url,omitempty"`
	// a failed request's HTTP status; absent when it got none (network error, a resource load WebKit reports without one)
	Status *int `json:"status,omitempty"`
	// what made the request: fetch, xhr, document (the page itself), or the element (img, script, link…)
	Resource *string `json:"resource,omitempty"`
}

// PageLogPrevious: the log of the page easl last released (after `since` when it names that page), as it was then; returned until the page loads another document after the reload, and until `since` names the current document
type PageLogPrevious struct {
	// ISO 8601
	ReleasedAt *string        `json:"releasedAt,omitempty"`
	URL        *string        `json:"url,omitempty"`
	Errors     *int           `json:"errors,omitempty"`
	Warnings   *int           `json:"warnings,omitempty"`
	Entries    []PageLogEntry `json:"entries,omitempty"`
	Omitted    *int           `json:"omitted,omitempty"`
	Dropped    *int           `json:"dropped,omitempty"`
	Reloaded   *bool          `json:"reloaded,omitempty"`
	Cursor     *string        `json:"cursor,omitempty"`
	Vitals     map[string]any `json:"vitals,omitempty"`
}

type PageLogVitalsLongTasks struct {
	Count   *int     `json:"count,omitempty"`
	TotalMs *float64 `json:"totalMs,omitempty"`
}

// PageLogVitals: milliseconds from navigation start (CLS unitless); null when not measured yet or not measured by WebKit (then named in `unsupported`), never a stand-in zero
type PageLogVitals struct {
	Lcp              *float64                `json:"lcp,omitempty"`
	Cls              *float64                `json:"cls,omitempty"`
	LongTasks        *PageLogVitalsLongTasks `json:"longTasks,omitempty"`
	Fcp              *float64                `json:"fcp,omitempty"`
	Ttfb             *float64                `json:"ttfb,omitempty"`
	DomContentLoaded *float64                `json:"domContentLoaded,omitempty"`
	Load             *float64                `json:"load,omitempty"`
	Unsupported      []string                `json:"unsupported,omitempty"`
}

// PageLog: What a browser tile's page reported since it loaded. Main frame only; a new document (load, reload) starts over.
type PageLog struct {
	// false: the tile has no page now (never shown or rendered, or released while out of view); `view.render` loads it
	Loaded bool `json:"loaded"`
	// how WebKit runs the page now: visible (on screen, rAF at the display's rate), hidden (nobody sees it: no rAF, timers throttled more the longer it stays hidden), driven (kept running for an agent though nobody sees it: rAF irregular and slower), released (no page) One of "visible", "hidden", "driven", "released".
	Visibility *string `json:"visibility,omitempty"`
	// the log of the page easl last released (after `since` when it names that page), as it was then; returned until the page loads another document after the reload, and until `since` names the current document
	Previous *PageLogPrevious `json:"previous,omitempty"`
	URL      *string          `json:"url,omitempty"`
	// exceptions, console errors and failed requests since the page loaded
	Errors   *int `json:"errors,omitempty"`
	Warnings *int `json:"warnings,omitempty"`
	// oldest first, the latest 100 (after `since`); the page keeps its last 200 errors and warnings and last 200 other messages
	Entries []PageLogEntry `json:"entries,omitempty"`
	// older entries after `since` left out of `entries`
	Omitted *int `json:"omitted,omitempty"`
	// entries the page's buffers no longer hold
	Dropped *int `json:"dropped,omitempty"`
	// `since` named an earlier document: `entries` start at this one's beginning
	Reloaded *bool `json:"reloaded,omitempty"`
	// pass as `since` to read only what comes after; while released, the released page's (`previous.cursor`)
	Cursor *string `json:"cursor,omitempty"`
	// milliseconds from navigation start (CLS unitless); null when not measured yet or not measured by WebKit (then named in `unsupported`), never a stand-in zero
	Vitals *PageLogVitals `json:"vitals,omitempty"`
}

// MentionTarget is a union of JSON objects (variants: "object", "code", "dom", "terminal", "group", "image", "console", "note"); decode it as a generic map.
type MentionTarget = map[string]any

type Mention struct {
	ID       Id            `json:"id"`
	Target   MentionTarget `json:"target"`
	Label    string        `json:"label"`
	StagedAt string        `json:"stagedAt"`
	// target changed since staging
	Edited bool `json:"edited"`
}

type ResolvedMention struct {
	// mention id, for tray.commit
	ID Id `json:"id"`
	// stable reference, e.g. canvas:men_12@rev3
	Ref   string `json:"ref"`
	Label string `json:"label"`
	// compact text for prompt context: location, excerpt, relations
	Summary string `json:"summary"`
	// structured view: contents, encloses, overlaps, arrows
	Graph map[string]any `json:"graph,omitempty"`
}

// PromptMentionPoint: image tiles only: a pixel of the picture, in the image's own pixels from its top-left
type PromptMentionPoint struct {
	X int `json:"x"`
	Y int `json:"y"`
}

// PromptMention: A board object `agent.prompt` attaches for the receiving agent, as a Hyper-click would mention it: a code tile's lines, an image tile's pixel, else the whole object
type PromptMention struct {
	// an object on the target terminal's board
	Object Id `json:"object"`
	// code tiles only: these lines of its file (at its pinned commit, if any). Without it a code tile showing a range mentions that range
	Lines *LineRange `json:"lines,omitempty"`
	// image tiles only: a pixel of the picture, in the image's own pixels from its top-left
	Point *PromptMentionPoint `json:"point,omitempty"`
}

type Agent struct {
	Tile Id `json:"tile"`
	// the board the terminal is on
	Board Id `json:"board"`
	// that board's root directory
	Root string  `json:"root"`
	Name *string `json:"name,omitempty"`
	// the integrated agent that reported (omp, claude, codex, gemini, opencode), or the program of an agent reporting by notification (aider; lifecycle `via: "notifications"`), else unknown
	Kind string `json:"kind"`
	// the title the program in the terminal set (OSC 0/2), e.g. Gemini CLI's "✋ Action Required (glow)"; absent when none
	Title *string `json:"title,omitempty"`
	// what runs in the terminal's foreground, named the way a person would (`gemini`, `opencode`, `cargo test`); absent at the shell's prompt
	Program   *string   `json:"program,omitempty"`
	SessionID *string   `json:"sessionId,omitempty"`
	Lifecycle Lifecycle `json:"lifecycle"`
	// the last command the terminal's shell finished (Ghostty's shell integration reports it); absent until one did
	LastCommand *TerminalCommand `json:"lastCommand,omitempty"`
}

type TerminalCommand struct {
	// the command line (its first line), as the shell integration titled the terminal while it ran; for an older block, the prompt row above its output
	Command *string `json:"command,omitempty"`
	// exit status; null when the shell didn't report one
	Exit *int `json:"exit,omitempty"`
	// how long it ran
	DurationMs *int `json:"durationMs,omitempty"`
	// `lastCommand` only
	FinishedAt *string `json:"finishedAt,omitempty"`
}

type BoardInfo struct {
	Board Id `json:"board"`
	// the board's root: a repository board's is its main checkout, whichever worktree opened it; otherwise the directory the board was last opened at
	Root string `json:"root"`
	// the root directory no longer exists (e.g. a removed checkout); the board is kept
	Archived bool `json:"archived"`
	// the board has a window in the app (only open boards accept `board` params)
	Open bool `json:"open"`
	// ISO 8601 time the board was last saved; absent for a board never saved
	UpdatedAt *string `json:"updatedAt,omitempty"`
	// object count
	Objects int `json:"objects"`
	// a repository board's common git directory (its identity: one board per repository)
	Repo *string `json:"repo,omitempty"`
	// a repository board's worktrees: its repository's live ones (main checkout first) and every one the board has seen (opened from, a terminal started in, a merged per-branch board's), one entry per worktree and branch
	Worktrees []WorktreeInfo `json:"worktrees,omitempty"`
}

type WorktreeInfo struct {
	// the worktree's top level
	Path string `json:"path"`
	// the branch checked out there (live), or last seen there; absent on a detached HEAD
	Branch *string `json:"branch,omitempty"`
	// the worktree exists with this branch checked out
	Live bool `json:"live"`
	// the repository's main checkout (the board root)
	Main bool `json:"main"`
	// the group holding what this branch's board held before boards were per repository (props.key `branch:<name>`)
	Region *Id `json:"region,omitempty"`
}

// Viewport: What the board's window shows: `rect` is the visible board area in board coordinates, `zoom` the magnification (1 = 100%, one point per board unit).
type Viewport struct {
	Rect Frame   `json:"rect"`
	Zoom float64 `json:"zoom"`
}

// RenderedObjectContentSize: the content's own extent in board points at the tile's width, below its title bar (tiles only; a zoomed tile's layout extent times its `zoom`); code: its range's rows and longest line under the header, the whole file without a range (what size "fit" shows)
type RenderedObjectContentSize struct {
	W *float64 `json:"w,omitempty"`
	H *float64 `json:"h,omitempty"`
}

// RenderedObjectOverflow: board points of content beyond the frame (right, bottom); absent when it fits
type RenderedObjectOverflow struct {
	X *float64 `json:"x,omitempty"`
	Y *float64 `json:"y,omitempty"`
}

// RenderedObject: Where an object landed in a rendered image and whether its content really painted.
type RenderedObject struct {
	ID   Id         `json:"id"`
	Type ObjectType `json:"type"`
	// image pixels, top-left origin; a tile's rect is its frame (its 26 pt title bar is inside it)
	PixelRect Frame `json:"pixelRect"`
	// placeholder: content not loaded in time or not renderable (a stand-in was drawn); failed: rendering errored One of "rendered", "placeholder", "failed".
	State string `json:"state"`
	// why a tile is a placeholder or failed
	Reason *string `json:"reason,omitempty"`
	// the content's own extent in board points at the tile's width, below its title bar (tiles only; a zoomed tile's layout extent times its `zoom`); code: its range's rows and longest line under the header, the whole file without a range (what size "fit" shows)
	ContentSize *RenderedObjectContentSize `json:"contentSize,omitempty"`
	// board points of content beyond the frame (right, bottom); absent when it fits
	Overflow *RenderedObjectOverflow `json:"overflow,omitempty"`
}

type HistoryEntry struct {
	// log cursor; pass the largest seen as `since`
	Seq int `json:"seq"`
	// board revision right after the entry (viewport/selection entries don't change it)
	Rev int `json:"rev"`
	// ISO 8601 time
	At string `json:"at"`
	// `user`, `system`, or `agent:<terminal tile id>`; a cascade is credited to whoever made the change that caused it
	Actor string `json:"actor"`
	// One of "created", "updated", "deleted", "viewport", "selection", "follow", "restart".
	Kind string `json:"kind"`
	// the object (for follow: the follow tile)
	ID   *Id         `json:"id,omitempty"`
	Type *ObjectType `json:"type,omitempty"`
	// one human-readable line
	Summary   string    `json:"summary"`
	Viewport  *Viewport `json:"viewport,omitempty"`
	Selection []Id      `json:"selection,omitempty"`
	// set on cascades of another change, saying why: a group `fit to its members` (one entry per group per revision, at its net change), an arrow's end freed because its `bound object obj_… deleted`
	Cause *string `json:"cause,omitempty"`
}
