package route

// Arrow caption chips as DrawingStyle.arrowLabel measures them (AppKit, Shantell Sans 15 pt,
// wrapped at 240 pt), for the captions these tests draw: what the Swift tests route with.
var measuredLabels = map[string]Size{
	"BridgeConfig.load()":            {145, 20},
	"RailsAgent loop":                {121, 20},
	"ambient candidate":              {141, 20},
	"bind actor":                     {81, 20},
	"calls":                          {40, 20},
	"cell actions":                   {88, 20},
	"code mode on":                   {109, 20},
	"collect tools":                  {94, 20},
	"consume grant":                  {113, 20},
	"continuation triggers":          {157, 20},
	"execute tool calls":             {131, 20},
	"execution terminal":             {139, 20},
	"far":                            {28, 20},
	"input 1":                        {55, 20},
	"input 2":                        {60, 20},
	"input 3":                        {60, 20},
	"input 4":                        {60, 20},
	"input 5":                        {58, 20},
	"input 6":                        {60, 20},
	"input 7":                        {60, 20},
	"input 8":                        {60, 20},
	"legacy email triggers":          {157, 20},
	"matching routines":              {135, 20},
	"mention or DM":                  {115, 20},
	"near":                           {41, 20},
	"nested action":                  {104, 20},
	"new chat task":                  {110, 20},
	"new-task outcome":               {139, 20},
	"preferred model":                {121, 20},
	"python action":                  {106, 20},
	"queued input":                   {100, 20},
	"read back (:656)":               {125, 20},
	"refresh preferred model":        {175, 20},
	"replyToUser action":             {138, 20},
	"route to channel":               {126, 20},
	"runShell action":                {114, 20},
	"setTimer action":                {117, 20},
	"shared thread policy":           {154, 20},
	"shrink gate":                    {88, 20},
	"start() writes":                 {104, 20},
	"step done":                      {78, 20},
	"step node":                      {78, 20},
	"stream attempt":                 {118, 20},
	"system prompt":                  {112, 20},
	"task completed":                 {116, 20},
	"text trigger":                   {90, 20},
	"this.forward() → bridgeFetch()": {222, 20},
	"timer occurrence":               {126, 20},
	"to tool schemas":                {121, 20},
	"tool schemas":                   {101, 20},
	"wake existing subtask":          {164, 20},
	"wake-up fires later":            {143, 20},
}
