// Generated by scripts/gen-clients.ts from schema/easl-api.json. Do not edit.

/// Each method's params (`params.properties`, in schema order) and the required ones: what
/// `ApiRouter` checks every request against, and names in its `invalid_params` errors.
enum ApiParams {
    /// The schema's `version` and the hash of the file this was generated from (`client.attach`).
    static let schemaVersion = 1
    static let schemaHash = "d30f958e2e99ecfe"

    static let methods: [String: (accepted: [String], required: [String])] = [
        "system.ping": ([], []),
        "app.metrics": (["reset", "watch"], []),
        "board.get": (["board", "since", "branch"], []),
        "board.history": (["board", "since", "limit", "kinds"], []),
        "board.list": ([], []),
        "board.open": (["root", "select"], ["root"]),
        "board.export": (["board", "path"], []),
        "object.get": (["id", "as", "since"], ["id"]),
        "object.find": (["board", "key", "keyPrefix", "type", "status", "as"], []),
        "object.create": (["board", "type", "props", "frame", "size", "parent", "caller"], ["type", "props"]),
        "object.update": (["id", "rev", "frame", "size", "props", "caller"], ["id"]),
        "object.upsert": (["board", "key", "type", "props", "frame", "size", "caller"], ["key", "type", "props"]),
        "object.delete": (["id", "caller"], ["id"]),
        "object.measure": (["board", "type", "props", "width", "caller"], ["type", "props"]),
        "object.reload": (["id", "timeoutMs", "caller"], ["id"]),
        "object.batch": (["board", "ops", "caller"], ["ops"]),
        "layout.place": (["id", "near", "side", "gap", "align", "caller"], ["id", "near"]),
        "layout.stack": (["ids", "direction", "gap", "wrapAt", "align", "origin", "caller"], ["ids"]),
        "layout.translate": (["ids", "dx", "dy", "caller"], ["ids", "dx", "dy"]),
        "layout.grid": (["cells", "colGap", "rowGap", "colAlign", "rowAlign", "origin", "caller"], ["cells"]),
        "layout.check": (["board", "ids", "rect", "caller"], []),
        "tray.list": (["board"], []),
        "tray.stage": (["target", "board"], ["target"]),
        "tray.unstage": (["id"], ["id"]),
        "tray.drain": (["board", "caller", "peek", "prompt"], []),
        "tray.commit": (["board", "ids"], ["ids"]),
        "agent.report": (["tile", "kind", "state", "message", "seq", "source", "call", "final", "serial", "error"], ["tile", "kind", "state"]),
        "agent.report_session": (["tile", "kind", "sessionId", "sessionPath"], ["tile", "kind"]),
        "agent.release": (["tile", "kind", "source"], ["tile", "kind"]),
        "agent.list": ([], []),
        "agent.prompt": (["target", "text", "mentions", "caller", "force"], ["target", "text"]),
        "agent.wait": (["target", "until", "timeoutMs"], ["target"]),
        "agent.read": (["target", "lines", "since", "block", "final"], ["target"]),
        "follow.report": (["tile", "path", "range", "changes", "action"], ["tile", "path", "action"]),
        "view.attention": (["id", "message", "clear", "caller"], ["id"]),
        "view.get": (["board"], []),
        "view.open_url": (["url", "board", "caller"], ["url"]),
        "view.render": (["board", "target", "scale", "full", "exclude", "padding", "out", "format", "timeoutMs"], ["target"]),
        "view.snapshot": (["board", "out", "format"], []),
        "events.subscribe": (["board", "events"], []),
        "client.attach": (["version", "schema", "app", "host", "serves", "boards", "focused"], ["version", "schema", "serves"]),
        "text.measure": (["items", "board"], ["items"]),
    ]
}
