#!/usr/bin/env bun
// Generates typed clients (and the app's param table) from schema/easl-api.json, and sets the
// clients' and the Claude Code plugin's package versions to VERSION.
//   bun scripts/gen-clients.ts          write generated files
//   bun scripts/gen-clients.ts --check  exit 1 if generated files are stale
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { join } from "node:path";

type Schema = {
  type?: string | string[];
  $ref?: string;
  const?: unknown;
  enum?: unknown[];
  oneOf?: Schema[];
  properties?: Record<string, Schema>;
  required?: string[];
  items?: Schema;
  description?: string;
  default?: unknown;
  additionalProperties?: Schema | boolean;
};

// `resend`: a read the clients re-send after the connection drops mid-call (see RESEND_METHODS).
type Method = { description: string; params: Schema; result: Schema; resend?: boolean };
type Catalog = { version: number; errors: Record<string, string>; definitions: Record<string, Schema>; methods: Record<string, Method> };

const root = join(import.meta.dir, "..");
const catalog: Catalog = JSON.parse(readFileSync(join(root, "schema/easl-api.json"), "utf8"));
const HEADER = "Generated by scripts/gen-clients.ts from schema/easl-api.json. Do not edit.";

// Params the clients fill from their own tile/board (explicit, else the terminal-tile
// environment) when omitted. Generated methods pass these keys to the client's call.
const ENV_DEFAULTS: Record<string, string> = { caller: "EASL_TILE_ID", board: "EASL_BOARD_ID" };

// Reads whose reply may be lost to an app restart and that are safe to send again.
const RESEND_METHODS = Object.entries(catalog.methods).filter(([, m]) => m.resend).map(([name]) => name);

const refName = (ref: string) => ref.replace("#/definitions/", "");
const pascal = (s: string) => s.replace(/(^|[._])([a-z])/g, (_, __, c: string) => c.toUpperCase());

// ---------- TypeScript ----------

function tsType(s: Schema, indent = ""): string {
  if (s.$ref) return refName(s.$ref);
  if (s.const !== undefined) return JSON.stringify(s.const);
  if (s.enum) return s.enum.map((v) => JSON.stringify(v)).join(" | ");
  if (s.oneOf) return s.oneOf.map((o) => tsType(o, indent)).join(" | ");
  switch (s.type) {
    case "string":
      return "string";
    case "number":
    case "integer":
      return "number";
    case "boolean":
      return "boolean";
    case "array": {
      const item = tsType(s.items ?? {}, indent);
      return `${item.includes(" | ") ? `(${item})` : item}[]`;
    }
    case "object": {
      const props = s.properties ?? {};
      const keys = Object.keys(props);
      if (keys.length === 0) return "Record<string, unknown>";
      const req = new Set(s.required ?? []);
      const inner = indent + "  ";
      const lines = keys.map((k) => {
        const doc = props[k].description ? `${inner}/** ${props[k].description} */\n` : "";
        return `${doc}${inner}${k}${req.has(k) ? "" : "?"}: ${tsType(props[k], inner)};`;
      });
      return `{\n${lines.join("\n")}\n${indent}}`;
    }
    default:
      return "unknown";
  }
}

function genTs(): string {
  const out: string[] = [`// ${HEADER}`, "", `export const SCHEMA_VERSION = ${catalog.version};`, ""];
  for (const [name, def] of Object.entries(catalog.definitions)) {
    if (def.description) out.push(`/** ${def.description} */`);
    out.push(`export type ${name} = ${tsType(def)};`, "");
  }
  const namespaces = new Map<string, { types: string[]; bodies: string[] }>();
  for (const [method, m] of Object.entries(catalog.methods)) {
    const P = `${pascal(method)}Params`;
    const R = `${pascal(method)}Result`;
    out.push(`export type ${P} = ${tsType(m.params)};`);
    out.push(`export type ${R} = ${tsType(m.result)};`, "");
    const [ns, fn] = method.split(".");
    const envKeys = Object.keys(m.params.properties ?? {}).filter((k) => k in ENV_DEFAULTS);
    const optional = (m.params.required ?? []).length === 0 ? "?" : "";
    const entry = namespaces.get(ns) ?? { types: [], bodies: [] };
    entry.types.push(`    /** ${m.description} */`, `    ${fn}(params${optional}: ${P}): Promise<${R}>;`);
    entry.bodies.push(`      ${fn}: (params${optional}: ${P}) => call(${JSON.stringify(method)}, params ?? {}, ${JSON.stringify(envKeys)}) as Promise<${R}>,`);
    namespaces.set(ns, entry);
  }
  out.push("/** Every API method, grouped by namespace (`api.board.get(...)`). */");
  out.push("export interface CanvasApi {");
  for (const [ns, { types }] of namespaces) out.push(`  ${ns}: {`, ...types, "  };");
  out.push("}", "");
  out.push("/** Params a client fills from its tile (`caller`) and board when the call omits them, with the env var each defaults from. */");
  out.push(`export const ENV_DEFAULTS: Record<string, string> = ${JSON.stringify(ENV_DEFAULTS)};`, "");
  out.push("/** `call` receives the method's auto-filled param names (keys of ENV_DEFAULTS it accepts). */");
  out.push("export function bindMethods(call: (method: string, params: object, envKeys: string[]) => Promise<unknown>): CanvasApi {");
  out.push("  return {");
  for (const [ns, { bodies }] of namespaces) out.push(`    ${ns}: {`, ...bodies, "    },");
  out.push("  };", "}", "");
  out.push(`export const METHODS = ${JSON.stringify(Object.keys(catalog.methods))} as const;`, "");
  out.push("/** Reads the client re-sends when the connection drops after sending (the app restarted), with `timeoutMs` reduced by the time already spent. */");
  out.push(`export const RESEND_METHODS: readonly string[] = ${JSON.stringify(RESEND_METHODS)};`, "");
  return out.join("\n");
}

// ---------- Python ----------

// Python keywords (not builtins like `id`/`type`, which are fine as parameter names).
const PY_KEYWORDS: Record<string, true> = Object.fromEntries(
  ["as", "from", "import", "class", "def", "return", "in", "is", "not", "and", "or", "global", "lambda", "pass", "raise", "try", "while", "with", "yield", "del", "for", "if", "else", "elif", "except", "finally", "assert", "break", "continue", "nonlocal", "async", "await", "None", "True", "False"].map((k) => [k, true]),
);
const pyName = (k: string) => (PY_KEYWORDS[k] ? `${k}_` : k);
const snake = (s: string) => s.replace(/([a-z0-9])([A-Z])/g, "$1_$2").toLowerCase();

function pyType(s: Schema): string {
  if (s.$ref) return `"${refName(s.$ref)}"`;
  if (s.const !== undefined) return `Literal[${JSON.stringify(s.const)}]`;
  if (s.enum) return `Literal[${s.enum.map((v) => JSON.stringify(v)).join(", ")}]`;
  if (s.oneOf) return `Union[${s.oneOf.map(pyType).join(", ")}]`;
  switch (s.type) {
    case "string":
      return "str";
    case "number":
      return "float";
    case "integer":
      return "int";
    case "boolean":
      return "bool";
    case "array":
      return `list[${pyType(s.items ?? {})}]`;
    case "object":
      return "dict[str, Any]";
    default:
      return "Any";
  }
}

function pyTypedDict(name: string, s: Schema): string[] {
  const props = s.properties ?? {};
  const req = new Set(s.required ?? []);
  const lines = [`class ${name}(TypedDict):`];
  if (s.description) lines.push(`    """${s.description}"""`);
  const keys = Object.keys(props);
  if (keys.length === 0) lines.push("    pass");
  for (const k of keys) {
    const t = pyType(props[k]);
    lines.push(`    ${k}: ${req.has(k) ? `Required[${t}]` : `NotRequired[${t}]`}`);
  }
  return lines;
}

function genPy(): string {
  const out: string[] = [
    `"""${HEADER}"""`,
    "",
    "from __future__ import annotations",
    "",
    "import functools",
    "import inspect",
    "import re",
    "from typing import Any, Callable, Literal, NotRequired, Required, TypedDict, TypeVar, Union",
    "",
    `SCHEMA_VERSION = ${catalog.version}`,
    `ENV_DEFAULTS = ${JSON.stringify(ENV_DEFAULTS)}`,
    "",
    '_Api = TypeVar("_Api")',
    "",
    "",
    "def _snake_case_hints(cls: type[_Api]) -> type[_Api]:",
    '    """A keyword spelled the wire\'s camelCase way (`timeoutMs`, as `easl methods` prints it) fails naming the snake_case parameter."""',
    "    for name, method in list(vars(cls).items()):",
    '        if name.startswith("_") or not callable(method):',
    "            continue",
    "        accepted = set(inspect.signature(method).parameters)",
    "",
    "        def hinted(method: Callable[..., Any] = method, accepted: set[str] = accepted) -> Callable[..., Any]:",
    "            @functools.wraps(method)",
    "            def call(self: Any, *args: Any, **kwargs: Any) -> Any:",
    "                for key in kwargs:",
    '                    snake = re.sub(r"(?<=[a-z0-9])([A-Z])", r"_\\1", key).lower()',
    '                    for hint in (snake, snake + "_"):',
    "                        if key not in accepted and hint in accepted:",
    "                            raise TypeError(f\"{method.__qualname__}() got an unexpected keyword argument '{key}'; the Python SDK spells it '{hint}'\")",
    "                return method(self, *args, **kwargs)",
    "",
    "            return call",
    "",
    "        setattr(cls, name, hinted())",
    "    return cls",
    "",
    "",
  ];
  // TypedDicts whose field names are Python keywords (e.g. "from") use the functional syntax.
  for (const [name, def] of Object.entries(catalog.definitions)) {
    const isObject = def.type === "object" && def.properties;
    if (isObject && Object.keys(def.properties!).some((k) => PY_KEYWORDS[k])) {
      const req = new Set(def.required ?? []);
      const fields = Object.entries(def.properties!).map(([k, v]) => `"${k}": ${req.has(k) ? `Required[${pyType(v)}]` : `NotRequired[${pyType(v)}]`}`);
      out.push(`${name} = TypedDict("${name}", {${fields.join(", ")}})`, "");
    } else if (isObject) {
      out.push(...pyTypedDict(name, def), "");
    } else {
      out.push(`${name} = ${pyType(def)}`, "");
    }
  }
  const namespaces = new Map<string, string[]>();
  for (const [method, m] of Object.entries(catalog.methods)) {
    const [ns, fn] = method.split(".");
    const props = m.params.properties ?? {};
    const req = new Set(m.params.required ?? []);
    const args = Object.keys(props)
      .sort((a, b) => Number(req.has(b)) - Number(req.has(a)))
      .map((k) => `${pyName(snake(k))}: ${pyType(props[k])}${req.has(k) ? "" : " | None = None"}`);
    const mapping = Object.keys(props).map((k) => `"${k}": ${pyName(snake(k))}`);
    const envKeys = Object.keys(props).filter((k) => k in ENV_DEFAULTS);
    const lines = [
      `    def ${pyName(fn)}(self${args.length ? ", *, " + args.join(", ") : ""}) -> dict[str, Any]:`,
      `        """${m.description}"""`,
      `        params = {${mapping.join(", ")}}`,
      `        return self._call(${JSON.stringify(method)}, params, ${JSON.stringify(envKeys)})`,
      "",
    ];
    namespaces.set(ns, [...(namespaces.get(ns) ?? []), ...lines]);
  }
  // The client drops None values and fills the env keys from its own tile/board.
  const callType = "Callable[[str, dict[str, Any], list[str]], Any]";
  for (const [ns, lines] of namespaces) {
    out.push("@_snake_case_hints", `class ${pascal(ns)}Api:`, `    def __init__(self, call: ${callType}) -> None:`, "        self._call = call", "", ...lines);
  }
  out.push("class GeneratedApi:", `    def __init__(self, call: ${callType}) -> None:`);
  for (const ns of namespaces.keys()) out.push(`        self.${pyName(ns)} = ${pascal(ns)}Api(call)`);
  out.push("", `METHODS = ${JSON.stringify(Object.keys(catalog.methods))}`, "");
  out.push("# Reads the client re-sends when the connection drops after sending (the app restarted), with `timeoutMs` reduced by the time already spent.");
  out.push(`RESEND_METHODS = ${JSON.stringify(RESEND_METHODS)}`, "");
  return out.join("\n");
}

// ---------- Swift (the app's param check) ----------

function genSwift(): string {
  const list = (keys: string[]) => `[${keys.map((k) => JSON.stringify(k)).join(", ")}]`;
  const out: string[] = [`// ${HEADER}`, "", "/// Each method's params (`params.properties`, in schema order) and the required ones: what"];
  out.push("/// `ApiRouter` checks every request against, and names in its `invalid_params` errors.");
  out.push("enum ApiParams {", "    static let methods: [String: (accepted: [String], required: [String])] = [");
  for (const [method, m] of Object.entries(catalog.methods)) {
    out.push(`        ${JSON.stringify(method)}: (${list(Object.keys(m.params.properties ?? {}))}, ${list(m.params.required ?? [])}),`);
  }
  out.push("    ]", "}", "");
  return out.join("\n");
}

// ---------- Go (easld's param table, error codes and record types) ----------

const GO_INITIALISMS = new Set(["id", "url", "html", "json", "uri"]);
/** `zmxSession` → `ZmxSession`, `id` → `ID`, `objectId` → `ObjectID`. */
function goName(key: string): string {
  const words = key.match(/[A-Z]?[a-z0-9]+|[A-Z]+(?![a-z])/g) ?? [];
  const name = words.map((w) => (GO_INITIALISMS.has(w.toLowerCase()) ? w.toUpperCase() : w[0].toUpperCase() + w.slice(1))).join("");
  if (!/^[A-Z][A-Za-z0-9]*$/.test(name)) throw new Error(`cannot derive a Go name from ${JSON.stringify(key)}`);
  return name;
}

const goComment = (text: string, indent = "") => text.split("\n").map((l) => `${indent}// ${l}`.trimEnd());

/** Pads the cells of each run of consecutive rows to common widths, as gofmt aligns them; a comment (string) row ends a run. */
function goAlign(rows: Array<string | string[]>, indent = "\t"): string[] {
  const out: string[] = [];
  let run: string[][] = [];
  const flush = () => {
    const widths: number[] = [];
    for (const cells of run) cells.forEach((c, i) => i < cells.length - 1 && (widths[i] = Math.max(widths[i] ?? 0, c.length)));
    for (const cells of run) out.push(indent + cells.map((c, i) => (i < cells.length - 1 ? c.padEnd(widths[i]) : c)).join(" "));
    run = [];
  };
  for (const row of rows) {
    if (typeof row === "string") {
      flush();
      out.push(row);
    } else run.push(row);
  }
  flush();
  return out;
}

function genGo(): string {
  const types: string[][] = [];
  const typeNames = new Set<string>();
  const claim = (name: string) => {
    if (typeNames.has(name)) throw new Error(`Go type name ${name} is used twice`);
    typeNames.add(name);
  };
  const allObjects = (s: Schema) => (s.oneOf ?? []).every((o) => o.type === "object" || (o.$ref && resolveGo(o).type === "object"));
  const resolveGo = (s: Schema): Schema => (s.$ref ? resolveGo(catalog.definitions[refName(s.$ref)]) : s);

  /** How a value of this schema is held: a scalar or struct takes a pointer when optional or nullable. */
  const pointable = (s: Schema): boolean => {
    const r = resolveGo(s);
    if (r.const !== undefined || r.enum) return true;
    if (r.oneOf) return false;
    const type = Array.isArray(r.type) ? r.type.find((t) => t !== "null") : r.type;
    return type === "string" || type === "number" || type === "integer" || type === "boolean" || (type === "object" && Object.keys(r.properties ?? {}).length > 0);
  };

  /** The Go type for `s`; inline records become structs named `name`, emitted into `types`. */
  function goType(s: Schema, name: string): string {
    if (s.$ref) return refName(s.$ref);
    if (s.const !== undefined) return typeof s.const === "string" ? "string" : typeof s.const === "boolean" ? "bool" : "float64";
    if (s.enum) return "string";
    if (s.oneOf) return allObjects(s) ? "map[string]any" : "any";
    const type = Array.isArray(s.type) ? s.type.find((t) => t !== "null") : s.type;
    switch (type) {
      case "string":
        return "string";
      case "number":
        return "float64";
      case "integer":
        return "int";
      case "boolean":
        return "bool";
      case "array":
        return `[]${goType(s.items ?? {}, name)}`;
      case "object": {
        if (Object.keys(s.properties ?? {}).length === 0) {
          const extra = s.additionalProperties;
          return typeof extra === "object" ? `map[string]${goType(extra, name)}` : "map[string]any";
        }
        claim(name);
        types.push(goStruct(name, s));
        return name;
      }
      default:
        return "any";
    }
  }

  function goStruct(name: string, s: Schema): string[] {
    const req = new Set(s.required ?? []);
    const rows: Array<string | string[]> = [];
    const seen = new Set<string>();
    for (const [key, prop] of Object.entries(s.properties ?? {})) {
      const field = goName(key);
      if (seen.has(field)) throw new Error(`${name}: two properties map to Go field ${field}`);
      seen.add(field);
      const nullable = Array.isArray(prop.type) && prop.type.includes("null");
      let type = goType(prop, name + field);
      if ((!req.has(key) || nullable) && pointable(prop)) type = `*${type}`;
      const notes = [prop.description, prop.enum ? `One of ${prop.enum.map((v) => JSON.stringify(v)).join(", ")}.` : undefined].filter((n) => n);
      if (notes.length > 0) rows.push(...goComment(notes.join(" "), "\t"));
      rows.push([field, type, `\`json:"${key}${req.has(key) ? "" : ",omitempty"}"\``]);
    }
    return [...(s.description ? goComment(`${name}: ${s.description}`) : []), `type ${name} struct {`, ...goAlign(rows), "}"];
  }

  for (const [name, def] of Object.entries(catalog.definitions)) {
    const doc = def.description ? goComment(`${name}: ${def.description}`) : [];
    if (def.oneOf) {
      claim(name);
      const kinds = def.oneOf.map((o) => JSON.stringify(resolveGo(o).properties?.kind?.const ?? refName(o.$ref ?? "")));
      const note = allObjects(def) ? `${name} is a union of JSON objects (variants: ${kinds.join(", ")}); decode it as a generic map.` : `${name} is a union.`;
      types.push([...(doc.length > 0 ? [...doc, "//"] : []), ...goComment(note), `type ${name} = ${allObjects(def) ? "map[string]any" : "any"}`]);
    } else if (def.enum) {
      claim(name);
      if (!def.enum.every((v) => typeof v === "string")) throw new Error(`${name}: only string enums are generated`);
      const consts = (def.enum as string[]).map((v) => [`${name}${v.split(/[^A-Za-z0-9]+/).map((w) => w[0].toUpperCase() + w.slice(1)).join("")}`, name, `= ${JSON.stringify(v)}`]);
      types.push([...doc, `type ${name} string`, "", "const (", ...goAlign(consts), ")"]);
    } else if (def.type === "object" && Object.keys(def.properties ?? {}).length > 0) {
      claim(name);
      types.push(goStruct(name, def));
    } else {
      claim(name);
      types.push([...doc, `type ${name} = ${goType(def, name)}`]);
    }
  }

  const list = (keys: string[]) => (keys.length === 0 ? "nil" : `[]string{${keys.map((k) => JSON.stringify(k)).join(", ")}}`);
  const out: string[] = [`// ${HEADER}`, "", "package api", ""];
  out.push("// SchemaVersion is the `version` of the schema this build was generated from.", `const SchemaVersion = ${catalog.version}`, "");
  out.push("// Error codes of a failed response's `error.code`, with what each means.", "const (");
  const errorRows: Array<string | string[]> = [];
  for (const [code, description] of Object.entries(catalog.errors)) {
    errorRows.push(...goComment(`${description}.`, "\t"));
    errorRows.push([`Code${goName(code.split("_").map((w, i) => (i === 0 ? w : w[0].toUpperCase() + w.slice(1))).join(""))}`, `= ${JSON.stringify(code)}`]);
  }
  out.push(...goAlign(errorRows), ")", "");
  out.push("// ParamSpec is a method's params: every name it accepts (`params.properties`, in schema order) and the required ones.", "type ParamSpec struct {", "\tAccepted []string", "\tRequired []string", "}", "");
  out.push("// Methods is each method's ParamSpec: what the server checks every request against, and names in its `invalid_params` errors.", "var Methods = map[string]ParamSpec{");
  for (const [method, m] of Object.entries(catalog.methods)) {
    out.push(`\t${JSON.stringify(method)}: {`, `\t\tAccepted: ${list(Object.keys(m.params.properties ?? {}))},`, `\t\tRequired: ${list(m.params.required ?? [])},`, "\t},");
  }
  out.push("}", "");
  for (const t of types) out.push(...t, "");
  return out.join("\n");
}

// ---------- Package versions (from VERSION, which scripts/bundle.sh also reads) ----------

const version = readFileSync(join(root, "VERSION"), "utf8").trim();
if (!/^\d+\.\d+\.\d+$/.test(version)) throw new Error(`VERSION must be MAJOR.MINOR.PATCH, not ${JSON.stringify(version)}`);

/** `file` with its first match of `pattern` (whose one group is the version) set to VERSION. */
function withVersion(rel: string, pattern: RegExp): string {
  const current = readFileSync(join(root, rel), "utf8");
  if (!pattern.test(current)) throw new Error(`no version in ${rel}`);
  return current.replace(pattern, (whole, old: string) => whole.replace(old, version));
}

const targets: Array<[string, string]> = [
  ["clients/ts/src/generated.ts", genTs()],
  ["clients/python/easl_sdk/_generated.py", genPy()],
  ["Sources/CanvasCore/ApiParams.swift", genSwift()],
  ["easld/internal/api/api_gen.go", genGo()],
  ["clients/python/pyproject.toml", withVersion("clients/python/pyproject.toml", /^version = "([^"]+)"$/m)],
  ["clients/ts/package.json", withVersion("clients/ts/package.json", /^  "version": "([^"]+)",$/m)],
  ["extensions/claude/.claude-plugin/plugin.json", withVersion("extensions/claude/.claude-plugin/plugin.json", /^  "version": "([^"]+)",$/m)],
];

const check = process.argv.includes("--check");
let stale = false;
for (const [rel, content] of targets) {
  const path = join(root, rel);
  const current = existsSync(path) ? readFileSync(path, "utf8") : "";
  if (current === content) continue;
  if (check) {
    console.error(`stale: ${rel}`);
    stale = true;
  } else {
    writeFileSync(path, content);
    console.log(`wrote ${rel}`);
  }
}
if (stale) process.exit(1);
